# Generated by Django 6.1.1 on 2026-09-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('volume_m3', models.DecimalField(decimal_places=3, max_digits=12)),
                ('pump_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_logs', to='infrastructure.asset')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('community', 'date', 'asset')},
            },
        ),
    ]
