# Generated by Django 6.1.1 on 2026-09-13 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('serial_number', models.CharField(max_length=80, unique=True)),
                ('meter_type', models.CharField(default='Mechanical', max_length=60)),
                ('meter_size', models.CharField(blank=True, help_text='e.g. 15mm, 1/2"', max_length=30)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('installation_location', models.CharField(blank=True, max_length=200)),
                ('initial_reading', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('current_reading', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available (in stock)'), ('INSTALLED', 'Installed (not yet active)'), ('ACTIVE', 'Active'), ('FAULTY', 'Faulty'), ('BLOCKED', 'Blocked'), ('REMOVED', 'Removed'), ('REPLACED', 'Replaced'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=12)),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=10)),
                ('last_inspection', models.DateField(blank=True, null=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('is_smart', models.BooleanField(default=False)),
                ('iot_device_id', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meters', to='customers.customer')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meters', to='customers.property')),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='meters.meter')),
            ],
            options={
                'ordering': ['meter_id'],
            },
        ),
        migrations.CreateModel(
            name='MeterReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_reading', models.DecimalField(decimal_places=3, max_digits=12)),
                ('initial_reading', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.TextField()),
                ('performed_on', models.DateField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_replacements', to='customers.customer')),
                ('new_meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacements_in', to='meters.meter')),
                ('old_meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacements_out', to='meters.meter')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_on'],
            },
        ),
        migrations.CreateModel(
            name='ReadingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('schedule_note', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('customers', models.ManyToManyField(blank=True, related_name='routes', to='customers.customer')),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('previous_reading', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('consumption', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reading_date', models.DateField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_distance_m', models.PositiveIntegerField(blank=True, help_text='Distance between reader GPS and customer GPS', null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='readings/%Y/%m/')),
                ('photo_url', models.URLField(blank=True)),
                ('device_id', models.CharField(blank=True, max_length=120)),
                ('client_reading_id', models.CharField(blank=True, help_text='Client-generated UUID for offline sync idempotency', max_length=80, null=True, unique=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual (office)'), ('MOBILE', 'Mobile app'), ('OCR', 'Photo OCR'), ('IOT', 'Smart meter'), ('ESTIMATED', 'Estimated')], default='MANUAL', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending validation'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('BILLED', 'Billed')], default='PENDING', max_length=10)),
                ('is_anomalous', models.BooleanField(default=False)),
                ('anomaly_flags', models.JSONField(blank=True, default=list)),
                ('anomaly_note', models.CharField(blank=True, max_length=300)),
                ('ocr_detected_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='customers.customer')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='meters.meter')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings_taken', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reading_date', '-id'],
                'indexes': [models.Index(fields=['meter', 'reading_date'], name='meters_mete_meter_i_3f3b18_idx'), models.Index(fields=['community', 'status'], name='meters_mete_communi_6ec6fa_idx')],
            },
        ),
    ]
