# Generated by Django 6.1.1 on 2026-09-13 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_customers', models.PositiveIntegerField(default=1000)),
                ('max_staff', models.PositiveIntegerField(default=20)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=80)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('boundary', models.JSONField(blank=True, help_text='GeoJSON polygon of the community boundary', null=True)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('water_source', models.CharField(blank=True, max_length=120)),
                ('water_system_type', models.CharField(choices=[('PIPED', 'Piped scheme'), ('BOREHOLE', 'Mechanised borehole'), ('SMALL_TOWN', 'Small-town water system'), ('HANDPUMP', 'Hand-pump'), ('MIXED', 'Mixed')], default='PIPED', max_length=20)),
                ('households_count', models.PositiveIntegerField(default=0)),
                ('meters_count', models.PositiveIntegerField(default=0)),
                ('service_status', models.CharField(choices=[('PENDING', 'Pending approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_communities', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='communities.subscriptionplan')),
            ],
            options={
                'verbose_name_plural': 'communities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='GHS', max_length=5)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('BIMONTHLY', 'Bi-monthly'), ('QUARTERLY', 'Quarterly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=12)),
                ('due_days', models.PositiveIntegerField(default=14, help_text='Days after bill issue before it is due')),
                ('late_penalty_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reminder_days', models.JSONField(blank=True, default=list, help_text='Days overdue at which reminders are sent, e.g. [7, 14, 21]')),
                ('disconnection_after_days', models.PositiveIntegerField(default=45)),
                ('disconnection_requires_approval', models.BooleanField(default=True)),
                ('anomaly_spike_percent', models.PositiveIntegerField(default=200, help_text='Flag when consumption exceeds this % of the running average')),
                ('anomaly_low_percent', models.PositiveIntegerField(default=30)),
                ('zero_consumption_streak', models.PositiveIntegerField(default=3)),
                ('notify_sms', models.BooleanField(default=True)),
                ('notify_whatsapp', models.BooleanField(default=False)),
                ('notify_email', models.BooleanField(default=True)),
                ('water_loss_target_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='communities.community')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
