# Generated by Django 6.1.1 on 2026-09-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitysettings',
            name='customer_portal_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communitysettings',
            name='customer_requests_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communitysettings',
            name='module_access',
            field=models.JSONField(blank=True, default=dict, help_text='Modules disabled per role: {role: [module keys]}'),
        ),
        migrations.AddField(
            model_name='communitysettings',
            name='online_payments_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communitysettings',
            name='show_usage_to_customers',
            field=models.BooleanField(default=True),
        ),
    ]
