# Generated by Django 6.1.1 on 2026-09-14 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_towns_and_public_reporting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('modules', models.JSONField(blank=True, default=list, help_text='Module keys from core/modules.py this role may use')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='communities.community')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('community', 'name')},
            },
        ),
    ]
