# Generated by Django 6.1.1 on 2026-09-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('charge_type', models.CharField(choices=[('SERVICE', 'Service charge'), ('MAINTENANCE_LEVY', 'Maintenance levy'), ('INFRASTRUCTURE_LEVY', 'Infrastructure levy'), ('OTHER', 'Other fixed charge')], default='SERVICE', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applies_to', models.JSONField(blank=True, default=list, help_text='Customer categories; empty = all')),
                ('is_active', models.BooleanField(default=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_charges', to='communities.community')),
            ],
            options={
                'ordering': ['charge_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INSTITUTIONAL', 'Institutional'), ('INDUSTRIAL', 'Industrial'), ('SCHOOL', 'School'), ('CHURCH', 'Church'), ('MOSQUE', 'Mosque'), ('PUBLIC_FACILITY', 'Public facility'), ('GOVERNMENT', 'Government facility')], default='RESIDENTIAL', max_length=20)),
                ('billing_mode', models.CharField(choices=[('FLAT', 'Flat rate per m³'), ('TIERED', 'Tiered (incremental blocks)'), ('SLAB', 'Slab (whole consumption priced at the band it lands in)')], default='TIERED', max_length=10)),
                ('flat_rate', models.DecimalField(decimal_places=4, default=0, help_text='Used when billing_mode = FLAT', max_digits=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_plans', to='communities.community')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('community', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TariffTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('from_m3', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('to_m3', models.DecimalField(blank=True, decimal_places=3, help_text='Blank = no upper limit', max_digits=10, null=True)),
                ('rate_per_m3', models.DecimalField(decimal_places=4, default=0, help_text='TIERED: price per m³ in this block', max_digits=10)),
                ('slab_amount', models.DecimalField(decimal_places=2, default=0, help_text='SLAB: fixed price if consumption falls in this band', max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='tariffs.tariffplan')),
            ],
            options={
                'ordering': ['plan', 'order', 'from_m3'],
            },
        ),
    ]
