# Generated by Django 6.1.1 on 2026-09-13 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('communities', '0001_initial'),
        ('customers', '0001_initial'),
        ('meters', '0001_initial'),
        ('tariffs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('tariff_name', models.CharField(blank=True, max_length=100)),
                ('previous_reading', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('current_reading', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('consumption', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('water_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maintenance_levy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('infrastructure_levy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=15)),
                ('lines', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='customers.customer')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='meters.meter')),
                ('reading', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill', to='meters.meterreading')),
                ('tariff_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tariffs.tariffplan')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Negative reduces the bill, positive increases it', max_digits=12)),
                ('reason', models.TextField()),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='approvals.approvalrequest')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='billing.bill')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('BIMONTHLY', 'Bi-monthly'), ('QUARTERLY', 'Quarterly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open (readings being collected)'), ('GENERATED', 'Bills generated'), ('CLOSED', 'Closed')], default='OPEN', max_length=12)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('bills_count', models.PositiveIntegerField(default=0)),
                ('total_billed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('community', 'name')},
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='billing.billingperiod'),
        ),
        migrations.CreateModel(
            name='DunningAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('REMINDER', 'Reminder'), ('SECOND_REMINDER', 'Second reminder'), ('FINAL_NOTICE', 'Final notice'), ('DISCONNECTION_WARNING', 'Disconnection warning'), ('DISCONNECTION', 'Disconnection')], max_length=25)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('days_overdue', models.PositiveIntegerField()),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='approvals.approvalrequest')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_actions', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['community', 'status'], name='billing_bil_communi_0ecccf_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['customer', 'status'], name='billing_bil_custome_32b915_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('customer', 'period')},
        ),
    ]
