# Generated by Django 6.1.1 on 2026-09-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('CARRIED_FORWARD', 'Carried forward into a later bill')], default='ISSUED', max_length=15),
        ),
    ]
