# Generated by Django 6.1.1 on 2026-09-13 12:22

import apps.accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('PLATFORM_SUPER_ADMIN', 'Platform Super Admin'), ('PLATFORM_FINANCE_ADMIN', 'Platform Finance Admin'), ('PLATFORM_OPERATIONS_ADMIN', 'Platform Operations Admin'), ('COMMUNITY_ADMIN', 'Community Admin'), ('COMMUNITY_FINANCE_OFFICER', 'Community Finance Officer'), ('COMMUNITY_WATER_MANAGER', 'Community Water Manager'), ('METER_READER', 'Meter Reader'), ('TECHNICIAN', 'Technician'), ('CUSTOMER', 'Customer / Household'), ('AUDITOR', 'Auditor'), ('CUSTOMER_SUPPORT', 'Customer Support')], default='CUSTOMER', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
