# Generated by Django 6.1.1 on 2026-09-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PLATFORM_SUPER_ADMIN', 'Platform Super Admin'), ('PLATFORM_FINANCE_ADMIN', 'Platform Finance Admin'), ('PLATFORM_OPERATIONS_ADMIN', 'Platform Operations Admin'), ('COMMUNITY_ADMIN', 'Community Admin'), ('COMMUNITY_FINANCE_OFFICER', 'Community Finance Officer'), ('COMMUNITY_WATER_MANAGER', 'Community Water Manager'), ('METER_READER', 'Meter Reader'), ('TECHNICIAN', 'Technician'), ('CUSTOMER', 'Customer / Household'), ('AUDITOR', 'Community Auditor'), ('CUSTOMER_SUPPORT', 'Customer Support'), ('FRONT_DESK_COLLECTOR', 'Front Desk Collector')], default='CUSTOMER', max_length=40),
        ),
    ]
