# Generated by Django 6.1.1 on 2026-09-14 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_front_desk_role'),
        ('communities', '0004_custom_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, help_text='Set when role=CUSTOM: the community-defined role this user holds', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='communities.communityrole'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PLATFORM_SUPER_ADMIN', 'Platform Super Admin'), ('PLATFORM_OPERATIONS_ADMIN', 'Platform Operations Admin'), ('COMMUNITY_ADMIN', 'Community Admin'), ('COMMUNITY_FINANCE_OFFICER', 'Community Finance Officer'), ('COMMUNITY_WATER_MANAGER', 'Community Water Manager'), ('METER_READER', 'Meter Reader'), ('TECHNICIAN', 'Technician'), ('CUSTOMER', 'Customer / Household'), ('AUDITOR', 'Community Auditor'), ('CUSTOMER_SUPPORT', 'Customer Support'), ('FRONT_DESK_COLLECTOR', 'Front Desk Collector'), ('CUSTOM', 'Custom role')], default='CUSTOMER', max_length=40),
        ),
    ]
