# Generated by Django 6.1.1 on 2026-09-13 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('asset_type', models.CharField(choices=[('BOREHOLE', 'Borehole'), ('WELL', 'Well'), ('TREATMENT_PLANT', 'Treatment plant'), ('RESERVOIR', 'Reservoir'), ('TANK', 'Tank'), ('PIPELINE', 'Pipeline'), ('PUMP', 'Pump'), ('GENERATOR', 'Generator'), ('SOLAR', 'Solar system'), ('CONTROL_PANEL', 'Control panel'), ('VALVE', 'Valve'), ('FILTER', 'Filter'), ('CHLORINATION', 'Chlorination equipment'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('DEGRADED', 'Degraded'), ('UNDER_MAINTENANCE', 'Under maintenance'), ('FAILED', 'Failed'), ('DECOMMISSIONED', 'Decommissioned')], default='OPERATIONAL', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacity', models.CharField(blank=True, help_text='e.g. 50 m³, 5 kW, 3 L/s', max_length=80)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('maintenance_interval_days', models.PositiveIntegerField(default=90)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('parent', models.ForeignKey(blank=True, help_text='Upstream asset in the network (source → treatment → reservoir → pipeline)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='infrastructure.asset')),
            ],
            options={
                'ordering': ['asset_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emergency_type', models.CharField(choices=[('PIPELINE_BURST', 'Major pipeline burst'), ('PUMP_FAILURE', 'Pump failure'), ('CONTAMINATION', 'Contamination'), ('SHORTAGE', 'Severe water shortage'), ('FLOODING', 'Flooding'), ('INFRASTRUCTURE_DAMAGE', 'Infrastructure damage'), ('OTHER', 'Other')], max_length=25)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESPONDING', 'Responding'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=12)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('declared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'emergencies',
                'ordering': ['-declared_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective (repair)'), ('INSPECTION', 'Inspection')], default='PREVENTIVE', max_length=12)),
                ('performed_on', models.DateField()),
                ('technician_name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parts_used', models.TextField(blank=True)),
                ('downtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('was_failure', models.BooleanField(default=False)),
                ('failure_cause', models.CharField(blank=True, max_length=200)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='infrastructure.asset')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_on'],
            },
        ),
        migrations.CreateModel(
            name='Outage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cause', models.CharField(max_length=200)),
                ('affected_area', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField()),
                ('expected_restoration', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESTORED', 'Restored'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('notify_customers', models.BooleanField(default=True)),
                ('customers_notified', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outages', to='infrastructure.asset')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('declared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterQualityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('testing_location', models.CharField(max_length=150)),
                ('tested_on', models.DateField()),
                ('laboratory', models.CharField(blank=True, max_length=150)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('turbidity_ntu', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('chlorine_mg_l', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('tds_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ecoli_cfu', models.IntegerField(blank=True, help_text='E. coli CFU/100 ml (0 = absent)', null=True)),
                ('coliform_cfu', models.IntegerField(blank=True, null=True)),
                ('result_summary', models.TextField(blank=True)),
                ('compliance_status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('ALERT', 'Alert – investigation required'), ('NON_COMPLIANT', 'Non-compliant')], default='COMPLIANT', max_length=15)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_tests', to='infrastructure.asset')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('tested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tested_on'],
            },
        ),
    ]
