# Generated by Django 6.1.1 on 2026-09-13 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('customers', '0001_initial'),
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('CUSTOMER_AGREEMENT', 'Customer agreement'), ('CONNECTION_FORM', 'Connection form'), ('METER_INSTALLATION', 'Meter installation document'), ('MAINTENANCE_REPORT', 'Maintenance report'), ('WATER_QUALITY_REPORT', 'Water-quality report'), ('RECEIPT', 'Payment receipt'), ('OFFICIAL_NOTICE', 'Official notice'), ('POLICY', 'Community policy'), ('OTHER', 'Other')], default='OTHER', max_length=25)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('external_url', models.URLField(blank=True, help_text='Link to a file stored in Drive/S3/Cloudinary (recommended on Railway, whose disk is ephemeral)')),
                ('description', models.TextField(blank=True)),
                ('is_public_to_customer', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='infrastructure.asset')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
