# Generated by Django 6.1.1 on 2026-09-13 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('tariffs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('property_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INSTITUTIONAL', 'Institutional'), ('INDUSTRIAL', 'Industrial'), ('SCHOOL', 'School'), ('CHURCH', 'Church'), ('MOSQUE', 'Mosque'), ('PUBLIC_FACILITY', 'Public facility'), ('GOVERNMENT', 'Government facility')], default='RESIDENTIAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['property_id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.CharField(editable=False, max_length=24, unique=True)),
                ('household_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('alternative_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('category', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INSTITUTIONAL', 'Institutional'), ('INDUSTRIAL', 'Industrial'), ('SCHOOL', 'School'), ('CHURCH', 'Church'), ('MOSQUE', 'Mosque'), ('PUBLIC_FACILITY', 'Public facility'), ('GOVERNMENT', 'Government facility')], default='RESIDENTIAL', max_length=20)),
                ('occupants', models.PositiveIntegerField(default=1)),
                ('connection_date', models.DateField(blank=True, null=True)),
                ('account_status', models.CharField(choices=[('PENDING', 'Pending connection'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DISCONNECTED', 'Disconnected'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(default='LOW', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('tariff_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='tariffs.tariffplan')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.property')),
            ],
            options={
                'ordering': ['household_name'],
            },
        ),
    ]
