# Generated by Django 6.1.1 on 2026-09-13 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('billing', '0001_initial'),
        ('communities', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK', 'Bank payment'), ('ONLINE', 'Online (card / gateway)'), ('CASH', 'Cash'), ('MANUAL', 'Manual entry'), ('AGENT', 'Payment agent'), ('USSD', 'USSD')], default='CASH', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('REFUNDED', 'Refunded')], default='SUCCESSFUL', max_length=12)),
                ('provider', models.CharField(blank=True, help_text='MTN MoMo, Vodafone Cash, Paystack, GCB ...', max_length=60)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('payer_phone', models.CharField(blank=True, max_length=30)),
                ('payer_name', models.CharField(blank=True, max_length=120)),
                ('paid_at', models.DateTimeField()),
                ('allocations', models.JSONField(blank=True, default=list, help_text='[{invoice, amount}] how the payment was applied')),
                ('notes', models.TextField(blank=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.bill')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('BILL', 'Bill'), ('PAYMENT', 'Payment'), ('ADJUSTMENT', 'Adjustment'), ('REFUND', 'Refund'), ('REVERSAL', 'Payment reversal'), ('WRITE_OFF', 'Debt write-off'), ('OPENING', 'Opening balance')], max_length=12)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.bill')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='customers.customer')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_via', models.JSONField(blank=True, default=list)),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Immutable copy of the receipt content at issue time')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='customers.customer')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='approvals.approvalrequest')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='communities.community')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='customers.customer')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['community', 'status'], name='payments_pa_communi_45d907_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'paid_at'], name='payments_pa_custome_96c6e6_idx'),
        ),
    ]
