# Generated by Django 6.1.1 on 2026-09-14 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_towns_and_public_reporting'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='source',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('PORTAL', 'Customer portal'), ('PUBLIC', 'Public link / QR')], default='STAFF', max_length=12),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='communities.town'),
        ),
    ]
