# Generated by Django 6.1.1 on 2026-09-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_towns_and_public_reporting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.CharField(choices=[('NO_WATER', 'No water'), ('METER_FAULT', 'Meter fault / damaged'), ('LEAK', 'Leak'), ('LOW_PRESSURE', 'Low pressure'), ('WATER_QUALITY', 'Dirty / smelly water'), ('ILLEGAL_CONNECTION', 'Illegal connection / tampering'), ('BILL_DISPUTE', 'Bill is incorrect'), ('NEW_CONNECTION', 'New connection request'), ('DISCONNECTION', 'Disconnection request'), ('METER_REPLACEMENT', 'Meter replacement request'), ('CONTACT_UPDATE', 'Update contact information'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
