# Generated by Django 6.1.1 on 2026-09-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=40, unique=True)),
                ('value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
